# Generated by Django 5.2.6 on 2025-09-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_meetingstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingstaff',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='attendance.meeting'),
        ),
    ]
