# Generated by Django 5.2.6 on 2025-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_meetingstaff_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
