# Generated by Django 5.2.6 on 2025-09-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_meeting_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingstaff',
            name='role',
            field=models.CharField(choices=[('scanner', 'Scanner'), ('member', 'Member')], default='scanner', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingstaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
