# Generated by Django 5.2.6 on 2025-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_meetingstaff_role_alter_meetingstaff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingstaff',
            name='role',
            field=models.CharField(default='Staff', max_length=50),
        ),
    ]
